#!/bin/bash

set -uo pipefail
trap 's=$?; echo "$0: Error on line "$LINENO": $BASH_COMMAND"; exit $s' ERR

LOCAL_PATH=/var/cache/pacman/pkg
REPO_NAME=custom

PACKAGES=${@:-pkg/*}
CHROOT="$PWD/root"

mkdir -p "$LOCAL_PATH"
mkdir -p "$CHROOT"

[[ -d "$CHROOT/root" ]] || mkarchroot -C /etc/pacman.conf "$CHROOT/root" base base-devel

for package in $PACKAGES; do
    cd "$package"
    rm -f *.pkg.tar.xz
    makechrootpkg -cur $CHROOT
    cd -
done

ln -sf "$REPO_NAME.db.tar.gz" "$LOCAL_PATH/$REPO_NAME.db"
ln -sf "$REPO_NAME.files.tar.gz" "$LOCAL_PATH/$REPO_NAME.files"

pkgs="${PACKAGES[@]}/"*.pkg.tar.xz
for pkg in $pkgs
do
    repo-add "$LOCAL_PATH/$REPO_NAME.db.tar.gz" $pkg
    ln -sf $PWD/$pkg /var/cache/pacman/pkg
done

